version: 2.1

node_image: &node_image
  circleci/node:10.1.0-browsers

executors:
  docker-exec:
    docker:
      - image: *node_image

jobs:
  lint:
    executor: docker-exec
    working_directory: ~/app
    steps:
      - run:
          name: install markdown linter
          command: npm i -g markdownlint-cli
      - run:
          name: run linter
          command: ./docs/

workflows:
  version: 2
  build:
    jobs:
      - lint
