version: 2.1

node_image: &node_image
  circleci/node:10.1.0

executors:
  docker-exec:
    docker:
      - image: *node_image

jobs:
  lint:
    executor: docker-exec
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: update-npm
          command: sudo npm install -g npm@latest
      - run:
          name: install markdown linter
          command: sudo npm i -g markdownlint-cli
      - run:
          name: run linter
          command: markdownlint ./docs/

workflows:
  version: 2
  build:
    jobs:
      - lint
